Models/Elemento.cs
namespace Proyecto_Final_ASPNET.Models
{
    public class Elemento
    {
        public Producto producto { get; set; }
        public int cantidad { get; set; }
    }
}

Models/Producto.cs
namespace Proyecto_Final_ASPNET.Models
{
    public class Producto
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public double precio { get; set; }
        public string foto { get; set; }
    }
}

Models/ProductoModelView.cs
namespace Proyecto_Final_ASPNET.Models
{
    public class ProductoModelView
    {
        private List<Producto> productos;
        public ProductoModelView()
        {
            productos = new List<Producto>() {
                new Producto {
                    id = 1,
                    nombre = "Queso",
                    precio = 15,
                    foto = "QuesoCatupiry.jpg"
                },
                new Producto {
                    id = 2,
                    nombre = "Atun",
                    precio = 7,
                    foto = "AtunSanLucas.jpg"
                },
                new Producto {
                    id = 3,
                    nombre = "Leche",
                    precio = 12,
                    foto = "LecheMiLeche.jpg"
                }
            };
        }

        public List<Producto> getTodos()
        {
            return productos;
        }

        public Producto getProducto(string codigo)
        {
            return productos.Single(p => p.id.Equals(codigo));
        }
    }
}

Controllers/CarritoController.cs
using Microsoft.AspNetCore.Mvc;
using Proyecto_Final_ASPNET.Conversor;
using Proyecto_Final_ASPNET.Models;

namespace Proyecto_Final_ASPNET.Controllers
{
    public class CarritoController : Controller
    {
        public IActionResult Index()
        {
            List<Elemento> carrito = ConversorSesion.ConvertirACsharp<List<Elemento>>(HttpContext.Session, "carrito");
            ViewBag.carrito = carrito;
            ViewBag.total = carrito.Sum(it => it.producto.precio * it.cantidad);
            return View();
        }
        public IActionResult Agregar(int id)
        {
            ProductoModelView productoModelView = new ProductoModelView();
            if (ConversorSesion.ConvertirACsharp<List<Elemento>>(HttpContext.Session, "carrito") == null)
            {
                List<Elemento> carrito = new List<Elemento>();
                carrito.Add(new Elemento { producto = productoModelView.getProducto(id.ToString()), cantidad = 1 });
                ConversorSesion.ConvertirAjson(HttpContext.Session, "carrito", carrito);
            }
            else
            {
                List<Elemento> carrito = ConversorSesion.ConvertirACsharp<List<Elemento>>(HttpContext.Session, "carrito");

                int indice = existe(id.ToString());
                if (indice != -1)
                {
                    carrito[indice].cantidad++;
                }
                else
                {
                    carrito.Add(new Elemento { producto = productoModelView.getProducto(id.ToString()), cantidad = 1 });
                }
                ConversorSesion.ConvertirAjson(HttpContext.Session, "carrito", carrito);
            }
            return RedirectToAction("Index");
        }
        [NonAction]
        private int existe(string id)
        {
            List<Elemento> carrito = ConversorSesion.ConvertirACsharp<List<Elemento>>(HttpContext.Session, "carrito");
            for (int i = 0; i < carrito.Count; i++)
                if (carrito[i].producto.id.Equals(id.ToString()))
                    return i;
            return -1;
        }
        [Route("EliminarElemento/{id}")]
        public IActionResult EliminarItem(string id)
        {
            List<Elemento> carrito = ConversorSesion.ConvertirACsharp<List<Elemento>>(HttpContext.Session, "carrito");
            int indice = existe(id.ToString());
            if (indice >= 0)
            {
                if (carrito[indice].cantidad > 1)
                {
                    carrito[indice].cantidad--;
                }
                else
                {
                    carrito.RemoveAt(indice);
                }
            }
            ConversorSesion.ConvertirAjson(HttpContext.Session, "carrito", carrito);
            return RedirectToAction("Index");
        }
    }
}

Controllers/TiendaController.cs
using Microsoft.AspNetCore.Mvc;
using Proyecto_Final_ASPNET.Models;
namespace Proyecto_Final_ASPNET.Controllers
{
    public class TiendaController : Controller
    {
        public IActionResult Index()
        {
            ProductoModelView productoModelView = new ProductoModelView();
            ViewBag.prods = productoModelView.getTodos();
            return View();
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Proyecto_Final_ASPNET.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Proyecto_Final_ASPNET.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Proyecto_Final_ASPNET.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proyecto_Final_ASPNET</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Proyecto_Final_ASPNET.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Proyecto_Final_ASPNET</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Proyecto_Final_ASPNET - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Carrito/Index.cshtml
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
    <h3 class="d-5"> Lista de productos en el carrito</h3>
    <div class="container">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4">
                <table class="table table-success">
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>Foto</th>
                        <th>Cantidad</th>
                        <th>Subtotal</th>
                        <th>Opciones</th>
                    </tr>
                    @foreach (var item in ViewBag.carrito)
                    {
                        <tr>
                            <td>@item.producto.id</td>
                            <td>@item.producto.nombre</td>
                            <td>@item.producto.precio</td>
                            <td>
                                <img src="~/imagenes/@item.producto.foto" height="50px" width="50px">
                            </td>
                            <td>@item.cantidad</td>
                            <td>@(item.producto.precio * item.cantidad)</td>
                            <td>
                                <a asp-controller="Carrito" asp-action="EliminarElemento" asp-route-id="@item.producto.id">Eliminar uno</a>
                            </td>
                        </tr>
                    }
                    <tr>
                        <td colspan="5" align="right">Total:</td>
                        <td colspan="2" align="left">@ViewBag.total</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

Views/Tienda/Index.cshtml
@using Proyecto_Final_ASPNET.Models;
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
    <h3 class="d-5"> Lsita de productos disponibles</h3>
    <table class="table table-success">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Foto</th>
            <th>Opciones</th>
        </tr>
        @foreach (Producto p in ViewBag.prods)
        {
            <tr>
                <td>@p.id</td>
                <td>@p.nombre</td>
                <td>@p.precio</td>
                <td>
                    <img src="~/imagenes/@p.foto" height="50px" width="50px">
                </td>
                <td>
                    <a href="@Url.Action("Agregar", "carrito", new { id = p.id})">Comprar ahora</a>
                </td>
            </tr>
        }
    </table>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>